<?php

return [
    'module_catalog' => [
        'dashboard.master_ops',
        'dashboard.green_belt',
        'dashboard.advertisement',
        'dashboard.monitoring',
        'dashboard.management',
        'green_belt.master',
        'green_belt.detail',
        'green_belt.supervisor_upload',
        'green_belt.my_uploads',
        'green_belt.outsourced_upload',
        'green_belt.watering_oversight',
        'green_belt.maintenance_cycles',
        'green_belt.supervisor_attendance',
        'green_belt.labour_entries',
        'green_belt.upload_review',
        'green_belt.issue_management',
        'green_belt.authority_view',
        'advertisement.site_master',
        'advertisement.campaign_management',
        'monitoring.upload',
        'monitoring.plan',
        'monitoring.history',
        'media.free_media_inventory',
        'task.request_intake',
        'task.progress_read',
        'task.management',
        'task.detail',
        'task.my_tasks',
        'task.worker_allocation',
        'governance.user_management',
        'governance.access_mappings',
        'governance.audit_logs',
        'governance.rejected_upload_cleanup',
        'governance.alert_panel',
        'reports.monthly',
        'settings.system',
        'task.worker_daily_entry',
        'commercial.client_media_library',
        'commercial.media_planning_inventory',
    ],
    'landing_routes' => [
        'dashboard.master_ops' => 'dashboard/master',
        'dashboard.green_belt' => 'dashboard/green-belt',
        'dashboard.advertisement' => 'dashboard/advertisement',
        'dashboard.monitoring' => 'dashboard/monitoring',
        'green_belt.watering_oversight' => 'oversight/watering',
        'green_belt.master' => 'belt/list',
        'green_belt.supervisor_upload' => 'upload/supervisor',
        'green_belt.my_uploads' => 'upload/my-list',
        'green_belt.outsourced_upload' => 'upload/outsourced',
        'green_belt.maintenance_cycles' => 'cycle/list',
        'green_belt.supervisor_attendance' => 'attendance/list',
        'green_belt.labour_entries' => 'labour/list',
        'green_belt.upload_review' => 'upload/list',
        'green_belt.issue_management' => 'issue/list',
        'monitoring.upload' => 'monitoring/upload',
        'monitoring.plan' => 'monitoringplan/list',
        'monitoring.history' => 'monitoring/history',
        'advertisement.site_master' => 'site/list',
        'advertisement.campaign_management' => 'campaign/list',
        'media.free_media_inventory' => 'freemedia/list',
        'task.request_intake' => 'request/list',
        'task.my_tasks' => 'task/my',
        'task.progress_read' => 'taskprogress/list',
        'task.management' => 'task/list',
        'green_belt.authority_view' => 'authority/view',
        'governance.user_management' => 'user/list',
        'governance.access_mappings' => 'role/list',
        'governance.audit_logs' => 'audit/list',
        'governance.rejected_upload_cleanup' => 'upload/cleanup-list',
        'reports.monthly' => 'report/belt-health',
        'settings.system' => 'settings/list',
        'dashboard.management' => 'dashboard/management',
        'governance.alert_panel'              => 'alert/list',
        'task.worker_daily_entry'             => 'workday/my-list',
        'commercial.client_media_library'     => 'media/client-library',
        'commercial.media_planning_inventory' => 'media/planning-view',
    ],
    'capability_matrix' => [
        'VIEW' => ['read'],
        'UPLOAD' => ['read', 'upload'],
        'APPROVE' => ['read', 'approve'],
        'MANAGE' => ['read', 'upload', 'approve', 'manage'],
    ],
];
